CREATE TABLE USER (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LOGIN TEXT NOT NULL DEFAULT '',
  PASSWORD TEXT NOT NULL DEFAULT '',
  REG_DATE TIMESTAMP DEFAULT NOW(),
  SCORE BIGINT DEFAULT 0
);

INSERT INTO USER (LOGIN, PASSWORD) VALUES ('admin', 'admin');

CREATE TABLE CITY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(330) NOT NULL UNIQUE,
  LATITUDE FLOAT NOT NULL DEFAULT 0,
  LONGITUDE FLOAT NOT NULL DEFAULT 0,
  COUNTRY_ID BIGINT DEFAULT 0
);

CREATE TABLE USER_TOKEN (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TOKEN VARCHAR(330) NOT NULL,
  USER_ID BIGINT NOT NULL,
  LAST_REQUEST TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE GAME (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  START_DATE TIMESTAMP DEFAULT NOW(),
  MAX_USERS INT NOT NULL DEFAULT 5,
  STATUS INT NOT NULL DEFAULT 0
);

CREATE TABLE COUNTRY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(330) NOT NULL,
  CODE VARCHAR(5) NOT NULL
);

CREATE TABLE GAME_STEP (
  GAME_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  STEP BIGINT NOT NULL DEFAULT 0,
  TYPE VARCHAR(330) NOT NULL,
  OBJECT_ID BIGINT NOT NULL
);
