0USE b11_13978243_co;

CREATE TABLE USER (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LOGIN TEXT NOT NULL DEFAULT '',
  PASSWORD TEXT NOT NULL DEFAULT '',
  REG_DATE TIMESTAMP DEFAULT NOW(),
  SCORE BIGINT DEFAULT 0
);

INSERT INTO USER (LOGIN, PASSWORD) VALUES ('admin', 'admin');

CREATE TABLE CITY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(330) NOT NULL UNIQUE,
  LATITUDE FLOAT NOT NULL DEFAULT 0,
  LONGITUDE FLOAT NOT NULL DEFAULT 0,
  COUNTRY_ID BIGINT DEFAULT 0
);

--ALTER TABLE CITY ADD COLUMN `COUNTY_ID` BIGINT DEFAULT 0 AFTER `LONGITUDE`;

INSERT INTO CITY (NAME) SELECT DISTINCT NAME FROM table0;

delete from table0 t where (select count(*) from table0 t2 where t2.login = t.login) > 1;

CREATE TABLE USER_TOKEN (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TOKEN TEXT NOT NULL,
  USER_ID BIGINT NOT NULL,
  LAST_REQUEST TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO USER_TOKEN (USER_ID, TOKEN) VALUES (1, 'TOKEN_TOKEN_TOKEN');

CREATE TABLE GAME (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  START_DATE TIMESTAMP DEFAULT NOW(),
  MAX_USERS INT NOT NULL DEFAULT 5,
  STATUS INT NOT NULL DEFAULT 0
);

CREATE TABLE GAME_USER (
  GAME_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL
);

CREATE TABLE GAME_CITY (
  GAME_ID BIGINT NOT NULL,
  CITY_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL
);

--CREATE TABLE RELATION (
--    PARENT_ID BIGINT NOT NULL,
--    CHILD_ID BIGINT NOT NULL,
--    TYPE TEXT NOT NULL
--);

CREATE TABLE COUNTRY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(330) NOT NULL,
  CODE VARCHAR(5) NOT NULL
);

CREATE TABLE GAME_STEP (
  GAME_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  STEP BIGINT NOT NULL DEFAULT 0,
  STEP_TYPE VARCHAR(330) NOT NULL,
  OBJECT_ID BIGINT NOT NULL DEFAULT 0
);
